#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : atomicwrites
Version  : 1.1.5
Release  : 1
URL      : http://pypi.debian.net/atomicwrites/atomicwrites-1.1.5.tar.gz
Source0  : http://pypi.debian.net/atomicwrites/atomicwrites-1.1.5.tar.gz
Summary  : Atomic file writes.
Group    : Development/Tools
License  : MIT
Requires: atomicwrites-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
python-atomicwrites
        ===================

%package python
Summary: python components for the atomicwrites package.
Group: Default

%description python
python components for the atomicwrites package.


%prep
%setup -q -n atomicwrites-1.1.5

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1502842153
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1502842153
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python2*/*
/usr/lib/python3*/*
